---
#debug or release
RunMode: debug

#server
HTTPPort: 10086
ReadTimeout: 10
WriteTimeout: 10

#app
PageSize: 10
JwtSecret: hsyqgw77&&&dghsd

#database
DBType: mysql
DBUser: root
# 前导0 会被当作 八进制数 viper.GetString() 后返回十进制数, 需要加引号
DBPassword: "03221006"
DBHost: 127.0.0.1:3306
DBName: tiny_website
DBTablePrefix: blog_

#redis config
RedisCfg:
  Host: 127.0.0.1:6379
  Password:
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 20
