---
#debug or release
RunMode: debug

#server
HTTPPort: 10086
ReadTimeout: 10
WriteTimeout: 10

#app
PageSize: 10
AccessJwtSecret: hsyqgw77&&&dghsd
RefreshJwtSecret: ahsdua17819cskcdskd
# access token expires after 15 minute
AccessTokenExpires: 15
## refresh token expires after 7 days
RefreshTokenExpires: 7

#database
DBType: mysql
DBUser: root
# 前导0 会被当作 八进制数 viper.GetString() 后返回十进制数, 需要加引号
DBPassword: "03221006"
DBHost: 127.0.0.1:3306
DBName: tiny_website
DBTablePrefix: blog_

#redis config
RedisCfg:
  # viper GetStringMap() method will return lowercase key
  addr: 127.0.0.1:6379
  network: tcp
  dialtimeout: 5
  password: ""
  maxidle: 30
  maxactive: 30
  adletimeout: 20
